### PR TITLE
Add the .gitignore file

### PR DESCRIPTION
**Pull request by dPliakos**
I added a `.gitignore` file (helps a lot) and run `update` and `audit fix` commands.

### CODE REVIEW

**Comment by apavlidi** [comment]
Did you install and run the application to check if any errors introduced by updating the libraries? Some of the libraries such as log4js changed its API so by updating the library the code breaks. So either we update certain libraries that are backward compatible, or we have to change certain areas of the code.
The .gitignore file is necessary and thanks for pointing that out, I am really suprised we didn`t have one.

**Comment by dPliakos** [comment]
I have problems with my virtual box installation.  I was hopping to have that fixed before the review.
Can you validate it? If not, let me just remote the update commits until I fix my setup.

**Comment by apavlidi** [comment]
Sure I can help you, head to the slack channel and PM me so we can tackle the problem together.

**Comment by dPliakos** [comment]
Thanks! I'm sending you at slack

**Comment by dPliakos** [comment]
A removed the updates, for now. I will do another PR for the updates.

**Pull request closed without merging**
